(function () {
  'use strict';

  const actionPermissions = {
    'submit-readiness': 'submitReadiness', 'readiness-pass': 'reviewReadiness', 'readiness-return': 'reviewReadiness', 'correction-resubmit': 'correctRequest',
    'submit-court': 'submitCourt', 'court-under-review': 'recordCourtResult', 'court-correction': 'recordCourtResult', 'court-correction-resubmit': 'submitCourt', 'court-rejected': 'recordCourtResult', 'court-issued': 'recordCourtResult',
    'agency-register': 'agencyRegister', 'agency-forward': 'agencyForward', 'got-receive': 'gotReceive', 'review-start': 'reviewWarrant', 'review-return': 'reviewWarrant', 'review-resubmit': 'correctReview', 'review-complete': 'reviewWarrant',
    'dispatch-prepare': 'prepareDispatch', 'dispatch-postal': 'prepareDispatch', 'dispatch-manual': 'prepareDispatch', 'add-tracking': 'prepareDispatch', 'tracking-sync': 'prepareDispatch', 'dispatch-resend': 'prepareDispatch', 'manual-received': 'prepareDispatch', 'manual-refused': 'prepareDispatch',
    'enforcement-not-found': 'recordEnforcement', 'enforcement-arrest': 'recordEnforcement', 'enforcement-joint-arrest': 'recordEnforcement', 'enforcement-pacc-arrest': 'recordEnforcement', 'enforcement-owner-joint': 'recordEnforcement', 'enforcement-detained': 'recordEnforcement', 'enforcement-deceased': 'recordEnforcement', 'enforcement-expired': 'recordEnforcement', 'verify-enforcement': 'verifyEnforcement',
    'enforcement-withdrawn-discovered': 'recordEnforcement', 'enforcement-escaped': 'recordEnforcement', 'enforcement-obstruction': 'recordEnforcement', 'enforcement-uncontactable': 'recordEnforcement', 'enforcement-direct-handover': 'recordEnforcement',
    'handover-schedule': 'manageHandover', 'handover-more-docs': 'manageHandover', 'handover-reschedule': 'manageHandover', 'handover-complete': 'manageHandover', 'handover-failed': 'manageHandover', 'handover-escaped': 'manageHandover',
    'termination-start': 'reviewTermination', 'termination-court-order': 'reviewTermination', 'confirm-court-effect': 'confirmCourtEffect', 'termination-ready': 'reviewTermination', 'activity7-submit': 'submitActivity7',
    'termination-notice': 'prepareTerminationNotice', 'agency-ack': 'agencyAcknowledge', 'withdrawal-submit': 'submitWithdrawal', 'withdrawal-more-docs': 'submitWithdrawal', 'withdrawal-resubmit': 'submitWithdrawal', 'withdrawal-order': 'submitWithdrawal', 'withdrawal-rejected': 'submitWithdrawal', 'withdrawal-court-transfer': 'submitWithdrawal',
    'day180-resolve': 'create', 'day180-screen': 'manageDay180', 'day180-block': 'manageDay180', 'day180-letter': 'manageDay180', 'day180-send': 'manageDay180', 'day180-receipt': 'manageDay180', 'day180-followup': 'manageDay180'
  };

  const actionRoles = {
    'submit-readiness': 'CaseOwner', 'readiness-pass': 'PaccSupervisor', 'readiness-return': 'PaccSupervisor', 'correction-resubmit': 'CaseOwner',
    'submit-court': 'CaseOwner', 'court-under-review': 'CaseOwner', 'court-correction': 'CaseOwner', 'court-correction-resubmit': 'CaseOwner', 'court-rejected': 'CaseOwner', 'court-issued': 'CaseOwner',
    'agency-register': 'AgencyCaseAdministrator', 'agency-forward': 'AgencyCaseAdministrator', 'got-receive': 'GotOfficer', 'review-start': 'GotReviewer', 'review-return': 'GotReviewer', 'review-resubmit': 'AgencyCaseAdministrator', 'review-complete': 'GotReviewer',
    'dispatch-prepare': 'GotOfficer', 'dispatch-postal': 'GotOfficer', 'dispatch-manual': 'GotOfficer', 'add-tracking': 'GotOfficer', 'tracking-sync': 'GotOfficer', 'dispatch-resend': 'GotOfficer', 'manual-received': 'GotOfficer', 'manual-refused': 'GotOfficer',
    'enforcement-not-found': 'CaseOwner', 'enforcement-arrest': 'CaseOwner', 'enforcement-joint-arrest': 'CaseOwner', 'enforcement-pacc-arrest': 'CaseOwner', 'enforcement-owner-joint': 'CaseOwner', 'enforcement-detained': 'CaseOwner', 'enforcement-deceased': 'CaseOwner', 'enforcement-expired': 'CaseOwner', 'verify-enforcement': 'GotReviewer',
    'enforcement-withdrawn-discovered': 'CaseOwner', 'enforcement-escaped': 'CaseOwner', 'enforcement-obstruction': 'CaseOwner', 'enforcement-uncontactable': 'CaseOwner', 'enforcement-direct-handover': 'CaseOwner',
    'handover-schedule': 'CaseOwner', 'handover-more-docs': 'CaseOwner', 'handover-reschedule': 'CaseOwner', 'handover-complete': 'CaseOwner', 'handover-failed': 'CaseOwner', 'handover-escaped': 'CaseOwner',
    'termination-start': 'GotReviewer', 'termination-court-order': 'CaseOwner', 'confirm-court-effect': 'CaseOwner', 'termination-ready': 'GotReviewer', 'activity7-submit': 'GotReviewer',
    'termination-notice': 'GotOfficer', 'agency-ack': 'AgencyCaseAdministrator', 'withdrawal-submit': 'AgencyCaseAdministrator', 'withdrawal-more-docs': 'AgencyCaseAdministrator', 'withdrawal-resubmit': 'AgencyCaseAdministrator', 'withdrawal-order': 'AgencyCaseAdministrator', 'withdrawal-rejected': 'AgencyCaseAdministrator', 'withdrawal-court-transfer': 'AgencyCaseAdministrator',
    'day180-resolve': 'CaseOwner', 'day180-screen': 'GotOfficer', 'day180-block': 'GotOfficer', 'day180-letter': 'GotOfficer', 'day180-send': 'GotOfficer', 'day180-receipt': 'GotOfficer', 'day180-followup': 'GotOfficer'
  };

  function isPresenter() { return new URLSearchParams(window.location.search).get('presenter') === '1'; }
  function now(state) {
    const next = new Date(state.clock);
    next.setMinutes(next.getMinutes() + 5);
    state.clock = next.toISOString();
    return state.clock;
  }
  function id(prefix, state) { return `${prefix}-${Date.parse(state.clock).toString(36)}-${Math.random().toString(36).slice(2, 6)}`; }
  function label(dimension, value) { return window.Activity9Seed.labels[dimension]?.[value] || value; }
  function roleName(role) { return window.Activity9Seed.roles[role]?.name || role; }

  function requirePermission(action, options) {
    const permission = actionPermissions[action];
    if (options.presenter && isPresenter()) return;
    if (action.startsWith('activity7-') && action !== 'activity7-submit') throw new Error('ผลกิจกรรมที่ 7 รับจากระบบต้นทาง และจำลองได้เฉพาะโหมดนำเสนอ');
    if (permission && !window.Activity9Store.hasPermission(permission)) throw new Error('คุณไม่มีสิทธิ์ดำเนินการนี้ กรุณาติดต่อผู้รับผิดชอบตามขั้นตอน');
  }

  function setDimension(record, dimension, value, state, action, detail) {
    const old = record.dimensions[dimension];
    record.dimensions[dimension] = value;
    record.audits.unshift({ id: id('AU', state), at: now(state), action, actorRole: state.currentRole, actor: roleName(state.currentRole), detail, dimension, from: label(dimension, old), to: label(dimension, value) });
  }

  function addAudit(record, state, action, detail, dimension = 'System') {
    record.audits.unshift({ id: id('AU', state), at: now(state), action, actorRole: state.currentRole, actor: roleName(state.currentRole), detail, dimension, from: '-', to: '-' });
  }

  function closeTasks(record, state, predicate = () => true) {
    record.tasks.filter((item) => item.status === 'Open' && predicate(item)).forEach((item) => {
      item.status = 'Completed'; item.completedAt = now(state); item.completedBy = roleName(state.currentRole);
    });
  }

  function openTask(record, state, type, title, role, tab, reason, dueDays = null, priority = 'Normal') {
    const existing = record.tasks.find((item) => item.status === 'Open' && item.type === type && item.assignedRole === role);
    if (existing) return existing;
    const createdAt = now(state);
    let dueDate = null;
    if (dueDays !== null) { const due = new Date(createdAt); due.setDate(due.getDate() + dueDays); dueDate = due.toISOString().slice(0, 10); }
    const item = { id: id('TK', state), recordId: record.id, type, title, assignedRole: role, assignedUnit: window.Activity9Seed.roles[role].unit, assignedUser: window.Activity9Seed.roles[role].name, createdAt, dueDate, status: 'Open', priority, actionTab: tab, reason, sourceEvent: type, completedAt: null, completedBy: null };
    record.tasks.push(item);
    return item;
  }

  function notify(record, state, type, recipientRole, summary, tab, deliveryStatus = 'PreviewOnly') {
    const notification = { id: id('NT', state), recordId: record.id, type, recipientRole, recipient: roleName(recipientRole), channels: ['Email', 'LINE', 'Push'], summary, link: `#/warrant/${record.id}?tab=${tab}`, createdAt: now(state), sentAt: deliveryStatus === 'Sent' ? state.clock : null, deliveryStatus, retryCount: 0, error: deliveryStatus === 'Failed' ? 'ช่องทางจำลองไม่พร้อมส่ง' : null, readAt: null };
    record.notifications.unshift(notification);
    state.notifications.unshift(notification);
  }

  function addDocument(record, state, type, name, status = 'Draft') {
    const previous = record.documents.filter((item) => item.type === type).sort((a, b) => b.version - a.version)[0];
    const document = { id: id('DOC', state), type, name, version: (previous?.version || 0) + 1, status, createdAt: now(state), createdBy: roleName(state.currentRole), attachments: [] };
    record.documents.unshift(document);
    return document;
  }

  function setCurrent(record, stage, task, role) {
    record.currentStage = stage;
    record.currentTask = task;
    record.responsible = role ? roleName(role) : '-';
  }

  const continueTrackingResults = ['NotFoundContinueTracking', 'Escaped', 'Obstruction', 'Uncontactable'];
  const continueTrackingDetail = { NotFoundContinueTracking: 'บันทึกผลไม่พบตัว', Escaped: 'บันทึกผลหลบหนีระหว่างติดตาม', Obstruction: 'บันทึกผลถูกขัดขวางการปฏิบัติงาน', Uncontactable: 'บันทึกผลติดต่อเจ้าของสำนวนไม่ได้' };
  function report(record, state, result, participation, payload) {
    const reportItem = { id: id('ER', state), occurredAt: payload.occurredAt || now(state), receivedAt: now(state), channel: payload.channel || 'โทรศัพท์', result, verification: continueTrackingResults.includes(result) ? 'Confirmed' : 'AwaitingEvidence', participation: participation || null, policeUnit: payload.policeUnit || 'สถานีตำรวจตัวอย่าง', informer: payload.informer || 'เจ้าหน้าที่ประสานงาน', receiver: roleName(state.currentRole), detail: payload.detail || 'บันทึกผลจากการประสานงาน', nextFollowUp: payload.nextFollowUp || null, custodyAgency: payload.custodyAgency || null, requiresHandover: payload.requiresHandover !== false };
    record.enforcementReports.unshift(reportItem);
    if (continueTrackingResults.includes(result)) {
      setDimension(record, 'enforcement', 'CoordinationTracking', state, continueTrackingDetail[result] || 'บันทึกผลการติดตาม', 'คงสถานะติดตามและสร้างกำหนดติดตามครั้งถัดไป');
      openTask(record, state, 'FollowEnforcement', 'ประสานติดตามผลตามหมาย', 'CaseOwner', 'enforcement', continueTrackingDetail[result] || 'ต้องติดตามต่อ', 7, 'High');
      setCurrent(record, 'ติดตามตามหมาย', 'ประสานติดตามผลครั้งถัดไป', 'CaseOwner');
    } else {
      addAudit(record, state, 'บันทึกผลจากการประสานงาน', 'เก็บเหตุการณ์ไว้รอตรวจเอกสารก่อนยืนยัน', 'Enforcement');
      openTask(record, state, 'VerifyEnforcement', 'ตรวจเอกสารยืนยันผลตามหมาย', 'GotReviewer', 'enforcement', 'มีผลสำคัญที่รอการตรวจเอกสาร', 2, 'Urgent');
      setCurrent(record, 'ตรวจผลตามหมาย', 'ตรวจเอกสารยืนยันผลที่ได้รับแจ้ง', 'GotReviewer');
    }
    notify(record, state, 'EnforcementResultRecorded', 'GotReviewer', 'มีผลการติดตามใหม่รอตรวจสอบใน E-CMIS', 'enforcement');
  }

  function trackingSync(record, state) {
    const attempt = record.dispatchAttempts.find((item) => item.current);
    if (!attempt || !attempt.trackingNumber) throw new Error('ยังไม่มีเลข Tracking สำหรับรอบส่งปัจจุบัน');
    const order = ['PostalAccepted', 'PostalInTransit', 'PostalOutForDelivery', 'PostalDelivered'];
    const currentIndex = order.indexOf(attempt.status);
    let nextStatus = order[Math.min(order.length - 1, currentIndex + 1)] || 'PostalAccepted';
    if (attempt.trackingNumber.endsWith('8') && attempt.events.length >= 2) nextStatus = 'PostalDeliveryFailed';
    if (attempt.trackingNumber.endsWith('0') && attempt.events.length >= 2) nextStatus = 'PostalReturned';
    if (attempt.status === nextStatus) { addAudit(record, state, 'ตรวจสถานะสิ่งส่ง', 'ไม่มี Event ใหม่ ไม่สร้างรายการซ้ำ', 'Dispatch'); return; }
    attempt.status = nextStatus;
    const detailMap = { PostalAccepted: 'รับฝากแล้ว', PostalInTransit: 'อยู่ระหว่างขนส่ง', PostalOutForDelivery: 'ออกนำจ่าย', PostalDelivered: 'นำจ่ายสำเร็จ', PostalDeliveryFailed: 'นำจ่ายไม่สำเร็จ', PostalReturned: 'ตีกลับผู้ส่ง' };
    attempt.events.push({ at: now(state), place: nextStatus === 'PostalDelivered' ? 'หน่วยงานตำรวจปลายทาง' : 'ศูนย์ไปรษณีย์ตัวอย่าง', detail: detailMap[nextStatus], status: nextStatus });
    setDimension(record, 'dispatch', nextStatus, state, 'รับสถานะสิ่งส่ง', `${detailMap[nextStatus]} — เป็นสถานะเอกสารเท่านั้น`);
    if (nextStatus === 'PostalDelivered') {
      closeTasks(record, state, (item) => ['TrackDispatch', 'ResendDispatch'].includes(item.type));
      openTask(record, state, 'FollowEnforcement', 'ประสานติดตามผลตามหมาย', 'CaseOwner', 'enforcement', 'เอกสารถูกนำจ่ายแล้ว เริ่มติดตามผลตามหมาย', 7, 'High');
      setCurrent(record, 'ติดตามตามหมาย', 'ประสานติดตามผลตามหมาย', 'CaseOwner');
      notify(record, state, 'DispatchDelivered', 'CaseOwner', 'หนังสือนำส่งหมายถูกนำจ่ายแล้ว กรุณาเริ่มติดตามผล', 'enforcement');
    } else if (['PostalDeliveryFailed', 'PostalReturned'].includes(nextStatus)) {
      openTask(record, state, 'ResendDispatch', 'ตรวจที่อยู่และจัดส่งใหม่', 'GotOfficer', 'dispatch', detailMap[nextStatus], 2, 'Urgent');
      setCurrent(record, 'แก้ไขการนำส่ง', 'ตรวจสาเหตุและจัดส่งใหม่', 'GotOfficer');
      notify(record, state, 'DispatchException', 'GotOfficer', 'การนำส่งมีปัญหา กรุณาตรวจสอบใน E-CMIS', 'dispatch', 'Failed');
    }
  }

  function perform(action, recordId, payload = {}, options = {}) {
    requirePermission(action, options);
    return window.Activity9Store.mutate(`action:${action}`, (state) => {
      if (options.presenter && isPresenter() && actionRoles[action]) state.currentRole = actionRoles[action];
      const record = state.records.find((item) => item.id === recordId);
      if (!record) throw new Error('ไม่พบแฟ้มที่ต้องการดำเนินการ');
      if (record.dimensions.termination === 'WithdrawnByCourt' && action !== 'view') throw new Error('แฟ้มนี้มีคำสั่งถอนหมายจากศาลแล้ว เปิดดูประวัติได้แต่ไม่สามารถเปลี่ยนสถานะ');

      switch (action) {
        case 'submit-readiness':
          if (!['Draft', 'ReadinessCorrectionRequested'].includes(record.dimensions.request)) throw new Error('สถานะปัจจุบันไม่สามารถส่งตรวจความพร้อมได้');
          addDocument(record, state, 'WarrantRequest', 'คำร้องขอออกหมายจับ', 'AwaitingReview'); closeTasks(record, state); setDimension(record, 'request', 'AwaitingReadinessReview', state, 'ส่งตรวจความพร้อม', 'บันทึก Version และส่งให้ผู้บังคับบัญชาชั้นต้นตรวจสอบ'); openTask(record, state, 'ReviewReadiness', 'ตรวจความพร้อมคำขอ', 'PaccSupervisor', 'court', 'เจ้าของสำนวนส่งตรวจความพร้อม', 2, 'High'); setCurrent(record, 'ตรวจความพร้อม', 'ตรวจความพร้อมก่อนยื่นศาล', 'PaccSupervisor'); notify(record, state, 'ReadinessReviewRequested', 'PaccSupervisor', 'มีคำขอหมายจับรอตรวจความพร้อม', 'court'); break;
        case 'readiness-pass':
          if (record.dimensions.request !== 'AwaitingReadinessReview') throw new Error('แฟ้มนี้ไม่ได้อยู่ระหว่างตรวจความพร้อม');
          closeTasks(record, state); setDimension(record, 'request', 'ReadyForCourt', state, 'ยืนยันพร้อมยื่นศาล', 'ข้อมูลและเอกสารผ่านการตรวจ'); openTask(record, state, 'SubmitCourt', 'ยื่นคำร้องต่อศาล', 'CaseOwner', 'court', 'ผู้ตรวจยืนยันพร้อมยื่นศาล', 3, 'High'); setCurrent(record, 'ยื่นศาล', 'ยื่นคำร้องต่อศาลด้วยตนเอง', 'CaseOwner'); notify(record, state, 'ReadyForCourt', 'CaseOwner', 'คำขอผ่านการตรวจและพร้อมยื่นศาล', 'court'); break;
        case 'readiness-return':
          if (record.dimensions.request !== 'AwaitingReadinessReview') throw new Error('แฟ้มนี้ไม่ได้อยู่ระหว่างตรวจความพร้อม');
          closeTasks(record, state); record.corrections.push({ id: id('CR', state), source: 'ReadinessReview', detail: payload.detail || 'กรุณาตรวจแก้ข้อมูลคำร้องและเอกสารประกอบ', assignedRole: 'CaseOwner', dueDate: payload.dueDate || '2026-08-08', status: 'Open' }); setDimension(record, 'request', 'ReadinessCorrectionRequested', state, 'ส่งกลับแก้ไข', payload.detail || 'เปิดประเด็นแก้ไขโดยไม่ลบ Version เดิม'); openTask(record, state, 'CorrectRequest', 'แก้ไขคำขอตามผลตรวจ', 'CaseOwner', 'court', payload.detail || 'มีรายการต้องแก้ไข', 3, 'Urgent'); setCurrent(record, 'แก้ไขคำขอ', 'แก้ไขและตอบประเด็นจากผู้ตรวจ', 'CaseOwner'); notify(record, state, 'RequestReturned', 'CaseOwner', 'คำขอถูกส่งกลับแก้ไข กรุณาเปิดดูรายละเอียด', 'court'); break;
        case 'correction-resubmit':
          record.corrections.filter((item) => item.status === 'Open').forEach((item) => { item.status = 'Resolved'; item.resolvedAt = now(state); item.response = payload.response || 'แก้ไขข้อมูลและแนบเอกสารฉบับใหม่แล้ว'; }); record.versions.push({ version: record.versions.length + 1, at: now(state), by: roleName(state.currentRole), note: 'แก้ไขตามผลตรวจและส่งใหม่' }); closeTasks(record, state); setDimension(record, 'request', 'AwaitingReadinessReview', state, 'ส่งกลับตรวจใหม่', 'ตอบประเด็นครบและเพิ่ม Version ใหม่'); openTask(record, state, 'ReviewReadiness', 'ตรวจความพร้อมคำขอฉบับแก้ไข', 'PaccSupervisor', 'court', 'เจ้าของสำนวนส่งฉบับแก้ไข', 2, 'High'); setCurrent(record, 'ตรวจความพร้อม', 'ตรวจฉบับแก้ไข', 'PaccSupervisor'); break;
        case 'submit-court':
        case 'court-correction-resubmit':
          if (!['ReadyForCourt', 'CourtRequestedCorrection'].includes(record.dimensions.request)) throw new Error('สถานะปัจจุบันยังไม่พร้อมยื่นศาล');
          if (action === 'court-correction-resubmit') { record.corrections.filter((item) => item.status === 'Open').forEach((item) => { item.status = 'Resolved'; item.response = 'แนบเอกสารเพิ่มเติมแล้ว'; }); addDocument(record, state, 'WarrantRequest', 'คำร้องขอออกหมายจับฉบับแก้ไข', 'Submitted'); }
          closeTasks(record, state); record.courtAttempts.push({ attempt: record.courtAttempts.length + 1, submittedAt: now(state), channel: 'ยื่นด้วยตนเอง', receiptNo: payload.receiptNo || `ศอ-รับ-${String(record.courtAttempts.length + 1).padStart(3, '0')}/69`, result: 'SubmittedManually', note: payload.note || 'เจ้าหน้าที่บันทึกผลการยื่น' }); setDimension(record, 'request', 'SubmittedManually', state, 'บันทึกยื่นคำร้องต่อศาล', 'ยื่นด้วยตนเองและเก็บหลักฐานการยื่น'); openTask(record, state, 'RecordCourtResult', 'ติดตามและบันทึกผลศาล', 'CaseOwner', 'court', 'ยื่นคำร้องแล้ว รอผลจากศาล', null, 'Normal'); setCurrent(record, 'รอผลศาล', 'ติดตามและบันทึกผลศาล', 'CaseOwner'); break;
        case 'court-under-review': setDimension(record, 'request', 'UnderCourtConsideration', state, 'บันทึกศาลรับไว้พิจารณา', 'บันทึกผลที่ได้รับจากศาล'); setCurrent(record, 'รอผลศาล', 'ติดตามผลการพิจารณา', 'CaseOwner'); break;
        case 'court-correction':
          record.corrections.push({ id: id('CR', state), source: 'Court', detail: payload.detail || 'ศาลขอเอกสารเพิ่มเติม', assignedRole: 'CaseOwner', dueDate: payload.dueDate || '2026-08-10', status: 'Open' }); closeTasks(record, state); setDimension(record, 'request', 'CourtRequestedCorrection', state, 'บันทึกศาลขอแก้ไข', 'เก็บผลในรอบยื่นเดิมและเปิดงานแก้ไข'); openTask(record, state, 'CourtCorrection', 'จัดทำเอกสารเพิ่มเติมตามที่ศาลขอ', 'CaseOwner', 'court', payload.detail || 'ศาลขอเอกสารเพิ่มเติม', 3, 'Urgent'); setCurrent(record, 'แก้ไขตามศาล', 'จัดทำเอกสารเพิ่มเติม', 'CaseOwner'); break;
        case 'court-rejected': closeTasks(record, state); setDimension(record, 'request', 'CourtRejected', state, 'บันทึกศาลไม่อนุมัติ', payload.reason || 'ศาลไม่อนุมัติในรอบยื่นปัจจุบัน'); openTask(record, state, 'ReviewCourtRejection', 'ตรวจเหตุผลศาลไม่อนุมัติ', 'CaseOwner', 'court', 'รับทราบผลและพิจารณารอบยื่นใหม่', 5, 'High'); setCurrent(record, 'ศาลไม่อนุมัติ', 'ตรวจเหตุผลและพิจารณาคำร้องรอบใหม่', 'CaseOwner'); break;
        case 'court-issued':
          if (!['SubmittedManually', 'UnderCourtConsideration'].includes(record.dimensions.request)) throw new Error('ต้องมีการยื่นศาลก่อนบันทึกผลออกหมาย');
          if (state.records.some((item) => item.id !== record.id && item.warrantNo === (payload.warrantNo || `มจ.${record.systemRef.slice(-3)}/2569`))) throw new Error('เลขหมายนี้มีอยู่ในทะเบียนแล้ว');
          record.warrantNo = payload.warrantNo || `มจ.${record.systemRef.slice(-3)}/2569`; record.issueDate = payload.issueDate || '2026-08-04'; record.due180 = '2027-01-31'; addDocument(record, state, 'CourtWarrant', 'หมายจับฉบับศาลประทับตรา', 'Issued'); closeTasks(record, state); setDimension(record, 'request', 'WarrantIssued', state, 'บันทึกศาลออกหมาย', `${record.warrantNo} พร้อมไฟล์หมายจากศาล`); setDimension(record, 'review', 'AwaitingAgencyRegistration', state, 'เริ่มกระบวนการตรวจรับหมาย', 'ส่งงานให้ธุรการสำนัก/กองลงทะเบียน'); openTask(record, state, 'AgencyRegister', 'ลงทะเบียนรับหมาย', 'AgencyCaseAdministrator', 'review', 'ศาลออกหมายแล้ว', 2, 'High'); setCurrent(record, 'ลงทะเบียนรับหมาย', 'ลงทะเบียนรับที่สำนัก/กอง', 'AgencyCaseAdministrator'); notify(record, state, 'WarrantIssued', 'AgencyCaseAdministrator', 'มีหมายจับใหม่รอลงทะเบียนรับ', 'review'); break;
        case 'agency-register': { const registerNo = payload.registerNo || 'ทะเบียนรับ สปท.1/2569'; record.agencyRegisterNo = registerNo; closeTasks(record, state); setDimension(record, 'review', 'AwaitingGotForward', state, 'ลงทะเบียนรับหมาย', registerNo); openTask(record, state, 'AgencyForward', 'ส่งต่อหมายให้ กอท.', 'AgencyCaseAdministrator', 'review', 'ลงทะเบียนรับหมายแล้ว', 1, 'High'); setCurrent(record, 'ส่งต่อ กอท.', 'บันทึกการส่งต่อหมายให้ กอท.', 'AgencyCaseAdministrator'); break; }
        case 'agency-forward': closeTasks(record, state); addDocument(record, state, 'InternalHandover', 'หลักฐานส่งต่อหมายให้ กอท.', 'Sent'); setDimension(record, 'review', 'GotReceived', state, 'ส่งต่อหมายให้ กอท.', 'เก็บเลขส่ง ผู้ส่ง และรายการเอกสาร'); openTask(record, state, 'GotReceive', 'ยืนยันรับหมายที่ กอท.', 'GotOfficer', 'review', 'สำนัก/กองส่งต่อหมายแล้ว', 1, 'High'); setCurrent(record, 'กอท. รับหมาย', 'ยืนยันรับเอกสารที่ กอท.', 'GotOfficer'); break;
        case 'got-receive': { const gotRegisterNo = payload.gotRegisterNo || 'กอท.ทะเบียน 1/2569'; record.gotRegisterNo = gotRegisterNo; closeTasks(record, state); setDimension(record, 'review', 'GotReceived', state, 'กอท. ยืนยันรับหมาย', `${gotRegisterNo} — บันทึกผู้รับ วันเวลา และหลักฐานรับ`); openTask(record, state, 'ReviewWarrant', 'ตรวจสอบหมายจับ', 'GotReviewer', 'review', 'กอท. รับเอกสารครบ', 2, 'High'); setCurrent(record, 'ตรวจรับหมาย', 'เริ่มตรวจ Checklist หมายจับ', 'GotReviewer'); break; }
        case 'review-start': setDimension(record, 'review', 'UnderReview', state, 'เริ่มตรวจหมายจับ', 'เปิด Checklist ตรวจข้อมูลและเอกสาร'); setCurrent(record, 'ตรวจรับหมาย', 'ตรวจข้อมูล เอกสาร และเลขหมายซ้ำ', 'GotReviewer'); break;
        case 'review-return': record.corrections.push({ id: id('CR', state), source: 'GotReview', detail: payload.detail || 'เอกสารอ่านไม่ได้หรือข้อมูลไม่ตรง', assignedRole: payload.assignedRole || 'AgencyCaseAdministrator', dueDate: payload.dueDate || '2026-08-09', status: 'Open' }); closeTasks(record, state); setDimension(record, 'review', 'ReturnedForCorrection', state, 'ส่งกลับแก้ไขเอกสารหมาย', payload.detail || 'เปิดประเด็นแก้ไขรายข้อ'); openTask(record, state, 'CorrectWarrantReview', 'แก้ไขเอกสารหมาย', payload.assignedRole || 'AgencyCaseAdministrator', 'review', payload.detail || 'เอกสารต้องแก้ไข', 3, 'Urgent'); setCurrent(record, 'แก้ไขเอกสารหมาย', 'แก้ไขและตอบประเด็นจาก กอท.', payload.assignedRole || 'AgencyCaseAdministrator'); break;
        case 'review-resubmit': record.corrections.filter((item) => item.status === 'Open').forEach((item) => { item.status = 'Resolved'; item.response = payload.response || 'แนบเอกสารฉบับใหม่แล้ว'; }); addDocument(record, state, 'CourtWarrant', 'สำเนาหมายจับฉบับแก้ไข', 'Resubmitted'); closeTasks(record, state); setDimension(record, 'review', 'Resubmitted', state, 'ส่งกลับมาตรวจใหม่', 'เพิ่ม Version เอกสารและเก็บฉบับเดิม'); openTask(record, state, 'ReviewWarrant', 'ตรวจหมายฉบับแก้ไข', 'GotReviewer', 'review', 'ได้รับเอกสารฉบับแก้ไข', 2, 'High'); setCurrent(record, 'ตรวจรับหมาย', 'ตรวจเอกสารฉบับแก้ไข', 'GotReviewer'); break;
        case 'review-complete': if (!['UnderReview', 'Resubmitted', 'GotReceived'].includes(record.dimensions.review)) throw new Error('ต้องรับและตรวจเอกสารก่อนยืนยันผล'); if (record.corrections.some((item) => item.status === 'Open')) throw new Error('ยังมีประเด็นแก้ไขที่ไม่ปิด'); closeTasks(record, state); setDimension(record, 'review', 'Complete', state, 'ยืนยันผลตรวจหมาย', 'Checklist ครบและไม่มีข้อบกพร่องค้าง'); openTask(record, state, 'PrepareDispatch', 'จัดทำหนังสือนำส่งหมาย', 'GotOfficer', 'dispatch', 'หมายผ่านการตรวจครบถ้วน', 2, 'High'); setCurrent(record, 'จัดทำหนังสือนำส่ง', 'จัดทำหนังสือนำส่งหมายให้ตำรวจ', 'GotOfficer'); notify(record, state, 'ReviewComplete', 'GotOfficer', 'หมายผ่านการตรวจและพร้อมจัดทำหนังสือนำส่ง', 'dispatch'); break;
        case 'dispatch-prepare': addDocument(record, state, 'PoliceDispatchLetter', 'หนังสือนำส่งหมายจับให้ตำรวจ', 'Ready'); setDimension(record, 'dispatch', 'ReadyToDispatch', state, 'จัดทำหนังสือนำส่ง', 'บันทึกเลขหนังสือ ผู้จัดทำ ผู้ลงนาม และเอกสารแนบ'); setCurrent(record, 'นำส่งหมาย', 'เลือกช่องทางและบันทึกการนำส่ง', 'GotOfficer'); break;
        case 'dispatch-postal': closeTasks(record, state); record.dispatchAttempts.push({ attempt: record.dispatchAttempts.length + 1, type: 'WarrantDispatch', channel: 'Postal', trackingNumber: null, sentAt: now(state), sentBy: roleName(state.currentRole), current: true, status: 'PostalAwaitingTrackingNumber', events: [] }); setDimension(record, 'dispatch', 'PostalAwaitingTrackingNumber', state, 'บันทึกส่งทางไปรษณีย์', 'รอกรอกเลข Tracking จากใบรับฝากครั้งเดียว'); openTask(record, state, 'TrackDispatch', 'กรอกเลข Tracking และติดตามสิ่งส่ง', 'GotOfficer', 'dispatch', 'นำฝากส่งแล้ว รอเลข Tracking', 1, 'High'); setCurrent(record, 'ติดตามการนำส่ง', 'กรอกเลข Tracking จากใบรับฝาก', 'GotOfficer'); break;
        case 'add-tracking': { const attempt = record.dispatchAttempts.find((item) => item.current); if (!attempt) throw new Error('ไม่พบรอบส่งปัจจุบัน'); if (attempt.trackingNumber) throw new Error('รอบส่งนี้บันทึกเลข Tracking แล้ว หากต้องเปลี่ยนให้สร้างรอบส่งใหม่'); const tracking = payload.trackingNumber || `TH6900${record.systemRef.slice(-6)}9`; if (!/^[A-Z]{2}[0-9]{10,13}$/.test(tracking)) throw new Error('รูปแบบเลข Tracking ไม่ถูกต้อง ตัวอย่าง TH690000000001'); if (state.records.some((item) => item.dispatchAttempts.some((row) => row.trackingNumber === tracking))) throw new Error('เลข Tracking นี้ถูกใช้กับรายการอื่นแล้ว'); attempt.trackingNumber = tracking; attempt.status = 'PostalAccepted'; attempt.events.push({ at: now(state), place: 'ที่ทำการไปรษณีย์ตัวอย่าง', detail: 'รับฝากแล้ว', status: 'PostalAccepted' }); setDimension(record, 'dispatch', 'PostalAccepted', state, 'บันทึกเลข Tracking', `${tracking} และแนบใบรับฝาก`); setCurrent(record, 'ติดตามการนำส่ง', 'ตรวจสถานะสิ่งส่ง', 'GotOfficer'); break; }
        case 'tracking-sync': trackingSync(record, state); break;
        case 'dispatch-resend': { const old = record.dispatchAttempts.find((item) => item.current); if (old) { old.current = false; old.supersededAt = now(state); old.supersededBy = roleName(state.currentRole); old.resendReason = payload.reason || 'แก้ไขที่อยู่และจัดส่งใหม่'; } record.dispatchAttempts.push({ attempt: record.dispatchAttempts.length + 1, type: old?.type || 'WarrantDispatch', channel: 'Postal', trackingNumber: null, sentAt: now(state), sentBy: roleName(state.currentRole), current: true, status: 'PostalAwaitingTrackingNumber', events: [], resendReason: payload.reason || 'จัดส่งใหม่หลังนำจ่ายไม่สำเร็จ' }); closeTasks(record, state); setDimension(record, 'dispatch', 'PostalAwaitingTrackingNumber', state, 'สร้างรอบส่งใหม่', 'เก็บ Tracking และ Event รอบเดิมครบถ้วน'); openTask(record, state, 'TrackDispatch', 'กรอกเลข Tracking รอบส่งใหม่', 'GotOfficer', 'dispatch', 'สร้างรอบส่งใหม่แล้ว', 1, 'Urgent'); break; }
        case 'dispatch-manual': record.dispatchAttempts.push({ attempt: record.dispatchAttempts.length + 1, type: 'WarrantDispatch', channel: 'Manual', sentAt: now(state), sentBy: payload.sender || roleName(state.currentRole), current: true, status: 'ManualAwaitingReceipt', destination: payload.destination || 'สถานีตำรวจตัวอย่าง', receiver: null, evidence: null, events: [] }); setDimension(record, 'dispatch', 'ManualAwaitingReceipt', state, 'บันทึกนำส่งด้วยตนเอง', 'รอยืนยันผู้รับและหลักฐานรับเอกสาร'); setCurrent(record, 'นำส่งด้วยตนเอง', 'บันทึกผลการรับเอกสาร', 'GotOfficer'); break;
        case 'manual-received': { const manual = record.dispatchAttempts.find((item) => item.current && item.channel === 'Manual'); if (!manual) throw new Error('ไม่พบรอบนำส่งด้วยตนเอง'); manual.status = 'ManualReceived'; manual.receiver = payload.receiver || 'นายผู้รับเอกสาร'; manual.receivedAt = now(state); manual.evidence = 'สำเนาคู่ฉบับประทับตรารับ.pdf'; setDimension(record, 'dispatch', 'ManualReceived', state, 'ยืนยันรับเอกสาร', 'เก็บชื่อผู้รับ ตำแหน่ง และหลักฐานรับ'); closeTasks(record, state); openTask(record, state, 'FollowEnforcement', 'ประสานติดตามผลตามหมาย', 'CaseOwner', 'enforcement', 'ปลายทางรับเอกสารแล้ว', 7, 'High'); setCurrent(record, 'ติดตามตามหมาย', 'ประสานติดตามผลตามหมาย', 'CaseOwner'); break; }
        case 'manual-refused': { const manual = record.dispatchAttempts.find((item) => item.current && item.channel === 'Manual'); if (!manual) throw new Error('ไม่พบรอบนำส่งด้วยตนเอง'); manual.status = 'RedeliveryRequired'; manual.failureReason = payload.reason || 'หน่วยงานปลายทางปฏิเสธรับ'; addAudit(record, state, 'บันทึกปฏิเสธรับเอกสาร', manual.failureReason, 'Dispatch'); openTask(record, state, 'ResendDispatch', 'ตรวจสอบและนำส่งใหม่', 'GotOfficer', 'dispatch', manual.failureReason, 2, 'Urgent'); setCurrent(record, 'แก้ไขการนำส่ง', 'ตรวจเหตุปฏิเสธและนำส่งใหม่', 'GotOfficer'); break; }
        case 'enforcement-not-found': report(record, state, 'NotFoundContinueTracking', null, payload); break;
        case 'enforcement-arrest': report(record, state, 'ArrestSucceeded', 'PoliceOnly', payload); break;
        case 'enforcement-joint-arrest': report(record, state, 'ArrestSucceeded', 'PaccAndPolice', payload); break;
        case 'enforcement-owner-joint': report(record, state, 'ArrestSucceeded', 'CaseOwnerAndPolice', payload); break;
        case 'enforcement-pacc-arrest': report(record, state, 'ArrestSucceeded', 'PaccOnly', payload); break;
        case 'enforcement-detained': report(record, state, 'Detained', null, { ...payload, custodyAgency: payload.custodyAgency || 'เรือนจำตัวอย่าง' }); break;
        case 'enforcement-deceased': report(record, state, 'EvidenceDeceased', null, payload); break;
        case 'enforcement-expired': report(record, state, 'EvidenceLimitationExpired', null, payload); break;
        case 'verify-enforcement': { const latest = record.enforcementReports[0]; if (!latest) throw new Error('ไม่มีผลการติดตามรอตรวจ'); if (latest.verification === 'Confirmed') throw new Error('ผลนี้ได้รับการยืนยันแล้ว'); latest.verification = 'Confirmed'; latest.confirmedAt = now(state); latest.confirmedBy = roleName(state.currentRole); closeTasks(record, state, (item) => item.type === 'VerifyEnforcement'); let status = record.dimensions.enforcement; if (latest.result === 'ArrestSucceeded') status = 'Arrested'; if (latest.result === 'Detained') status = 'Detained'; if (latest.result === 'EvidenceDeceased') status = 'Deceased'; if (latest.result === 'EvidenceLimitationExpired') status = 'LimitationExpired'; if (latest.result === 'WarrantRevokedDuringTracking') status = 'WarrantRevokedDuringTracking'; setDimension(record, 'enforcement', status, state, 'ยืนยันผลตามหมาย', 'ตรวจเอกสารและยืนยันผลแล้ว'); if (status === 'Arrested' || (status === 'Detained' && latest.requiresHandover)) { setDimension(record, 'handover', 'AwaitingProsecutorCoordination', state, 'เปิดกระบวนการส่งตัว', 'อยู่ในความควบคุมและต้องประสานอัยการ'); openTask(record, state, 'ManageHandover', 'ประสานนัดส่งตัวให้อัยการ', 'CaseOwner', 'handover', 'ผลจับกุม/อายัดตัวได้รับการยืนยัน', 1, 'Urgent'); setCurrent(record, 'ส่งตัวให้อัยการ', 'ประสานนัดส่งตัว', 'CaseOwner'); } else if (status === 'Detained') { openTask(record, state, 'FollowDetention', 'ติดตามการอายัดตัว', 'CaseOwner', 'enforcement', 'ยังไม่เข้าเงื่อนไขส่งอัยการ', null, 'High'); setCurrent(record, 'อายัดตัว', 'ติดตามสถานะการควบคุมตัว', 'CaseOwner'); } else if (['Deceased', 'LimitationExpired', 'WarrantRevokedDuringTracking'].includes(status)) { openTask(record, state, 'ReviewTermination', 'ตรวจเหตุและหลักฐานขอยุติ', 'GotReviewer', 'termination', 'มีผลยุติที่ยืนยันแล้ว', 3, 'High'); setCurrent(record, 'ตรวจเหตุยุติ', 'ตรวจหลักฐานเพื่อเสนออนุมัติ', 'GotReviewer'); } break; }
        case 'enforcement-withdrawn-discovered': report(record, state, 'WarrantRevokedDuringTracking', null, payload); break;
        case 'enforcement-escaped': report(record, state, 'Escaped', null, payload); break;
        case 'enforcement-obstruction': report(record, state, 'Obstruction', null, payload); break;
        case 'enforcement-uncontactable': report(record, state, 'Uncontactable', null, payload); break;
        case 'enforcement-direct-handover': { const reportItem = { id: id('ER', state), occurredAt: payload.occurredAt || now(state), receivedAt: now(state), channel: 'ตรวจสอบย้อนหลัง', result: 'ArrestSucceeded', verification: 'Confirmed', participation: 'PoliceOnly', policeUnit: payload.policeUnit || 'สถานีตำรวจตัวอย่าง', informer: payload.informer || 'เจ้าหน้าที่ประสานงาน', receiver: roleName(state.currentRole), detail: payload.detail || 'ตำรวจส่งตัวตรงอัยการโดย ป.ป.ท. ไม่ทราบล่วงหน้า (WAR010) — บันทึกเป็นข้อมูล Manual จากการตรวจสอบย้อนหลัง', nextFollowUp: null, custodyAgency: null, requiresHandover: false, dataSource: 'ManualRetroactiveVerification' }; record.enforcementReports.unshift(reportItem); setDimension(record, 'enforcement', 'Arrested', state, 'บันทึกผลจับกุมแบบตรวจสอบย้อนหลัง', 'ตำรวจส่งตัวตรงอัยการโดย ป.ป.ท. ไม่ทราบล่วงหน้า (WAR010) เป็นข้อมูล Manual จากการตรวจสอบ'); addDocument(record, state, 'ProsecutorReceipt', 'ใบรับตัวจากพนักงานอัยการ (ตรวจสอบย้อนหลัง)', 'Complete'); setDimension(record, 'handover', 'Completed', state, 'บันทึกส่งตัวสำเร็จแบบตรวจสอบย้อนหลัง', payload.receiptNo || 'ตรวจสอบย้อนหลังจากตำรวจ ไม่ผ่านการนัดหมายของ ป.ป.ท.'); openTask(record, state, 'ReviewTermination', 'ตรวจเหตุและหลักฐานขอยุติ', 'GotReviewer', 'termination', 'ส่งตัวให้อัยการสำเร็จแล้ว (ตรวจสอบย้อนหลัง)', 3, 'High'); setCurrent(record, 'ตรวจเหตุยุติ', 'ตรวจหลักฐานเพื่อเสนออนุมัติ', 'GotReviewer'); notify(record, state, 'DirectHandoverDiscovered', 'GotReviewer', 'พบว่าตำรวจส่งตัวตรงอัยการโดยไม่ทราบล่วงหน้า บันทึกแบบตรวจสอบย้อนหลัง', 'termination'); break; }
        case 'handover-schedule': if (!['Arrested', 'Detained'].includes(record.dimensions.enforcement)) throw new Error('ต้องยืนยันผลจับกุมหรืออายัดตัวที่ต้องส่งอัยการก่อน'); record.handoverAttempts.push({ attempt: record.handoverAttempts.length + 1, appointmentAt: payload.appointmentAt || '2026-08-06T09:30:00+07:00', prosecutorOffice: payload.prosecutorOffice || 'สำนักงานอัยการตัวอย่าง', result: 'AppointmentScheduled' }); setDimension(record, 'handover', 'AppointmentScheduled', state, 'บันทึกนัดส่งตัว', 'พนักงานอัยการเป็นผู้รับภายนอกระบบ'); setCurrent(record, 'ส่งตัวให้อัยการ', 'เตรียมตัวและเอกสารตามนัด', 'CaseOwner'); break;
        case 'handover-more-docs': setDimension(record, 'handover', 'ProsecutorRequestedDocuments', state, 'บันทึกอัยการขอเอกสารเพิ่ม', payload.detail || 'ขอเอกสารประกอบเพิ่มเติม'); openTask(record, state, 'ManageHandover', 'จัดเตรียมเอกสารเพิ่มเติมให้อัยการ', 'CaseOwner', 'handover', payload.detail || 'อัยการขอเอกสารเพิ่ม', 1, 'Urgent'); break;
        case 'handover-reschedule': setDimension(record, 'handover', 'AppointmentScheduled', state, 'เปลี่ยนนัดส่งตัว', 'บันทึกนัดใหม่โดยเก็บนัดเดิม'); record.handoverAttempts.push({ attempt: record.handoverAttempts.length + 1, appointmentAt: payload.appointmentAt || '2026-08-08T09:30:00+07:00', prosecutorOffice: 'สำนักงานอัยการตัวอย่าง', result: 'AppointmentScheduled', note: 'อัยการไม่พร้อมรับในนัดเดิม' }); break;
        case 'handover-complete': addDocument(record, state, 'ProsecutorReceipt', 'ใบรับตัวจากพนักงานอัยการ', 'Complete'); closeTasks(record, state); setDimension(record, 'handover', 'Completed', state, 'บันทึกส่งตัวสำเร็จ', payload.receiptNo || 'เลขรับตัว อก.69/001'); openTask(record, state, 'ReviewTermination', 'ตรวจเหตุและหลักฐานขอยุติ', 'GotReviewer', 'termination', 'ส่งตัวให้อัยการสำเร็จแล้ว', 3, 'High'); setCurrent(record, 'ตรวจเหตุยุติ', 'ตรวจหลักฐานเพื่อเสนออนุมัติ', 'GotReviewer'); notify(record, state, 'HandoverCompleted', 'GotReviewer', 'ส่งตัวให้อัยการสำเร็จ มีงานตรวจเหตุยุติ', 'termination'); break;
        case 'handover-failed': setDimension(record, 'handover', 'UnableToComplete', state, 'บันทึกส่งตัวไม่สำเร็จ', payload.reason || 'อัยการไม่รับตัว ต้องรายงานผู้บังคับบัญชา'); openTask(record, state, 'EscalateHandover', 'รายงานปัญหาการส่งตัว', 'PaccSupervisor', 'handover', payload.reason || 'ส่งตัวไม่สำเร็จ', 1, 'Urgent'); break;
        case 'handover-escaped': setDimension(record, 'handover', 'UnableToComplete', state, 'บันทึกหลบหนีระหว่างนำส่ง', 'เปิดงานเร่งด่วนและคงประวัติการจับกุม'); setDimension(record, 'enforcement', 'CoordinationTracking', state, 'กลับสู่การติดตามตามหมาย', 'ผู้ต้องหาหลบหนีระหว่างนำส่ง'); openTask(record, state, 'FollowEnforcement', 'ติดตามผู้ต้องหาหลบหนี', 'CaseOwner', 'enforcement', 'หลบหนีระหว่างนำส่ง', 0, 'Urgent'); break;
        case 'termination-start': setDimension(record, 'termination', 'ReviewingReasonAndEvidence', state, 'เริ่มตรวจเหตุยุติ', payload.reason || 'ตรวจความครบถ้วนและความตรงกันของหลักฐาน'); setCurrent(record, 'ตรวจเหตุยุติ', 'ตรวจเหตุ บุคคล และเอกสารประกอบ', 'GotReviewer'); break;
        case 'termination-court-order': record.courtEffect = { orderDate: payload.orderDate || '2026-08-01', effectiveDate: payload.effectiveDate || (options.presenter ? '2026-08-04' : '2026-08-10'), finalDate: payload.finalDate || '', orderNo: payload.orderNo || 'คส.ตัวอย่าง 1/2569', court: payload.court || record.court, documentId: addDocument(record, state, 'CourtOrder', 'สำเนาคำสั่งหรือคำพิพากษาศาล', 'Received').id, confirmedBy: null, confirmedAt: null }; setDimension(record, 'termination', 'AwaitingAdditionalInformation', state, 'บันทึกคำสั่งหรือคำพิพากษาศาล', 'รอวันที่มีผลและเจ้าของสำนวนยืนยัน'); openTask(record, state, 'ConfirmCourtEffect', 'ยืนยันคำสั่งศาลมีผล', 'CaseOwner', 'termination', 'ตรวจวันที่มีผลและไฟล์คำสั่ง', 5, 'High'); setCurrent(record, 'รอคำสั่งมีผล', 'เจ้าของสำนวนตรวจและยืนยันวันที่มีผล', 'CaseOwner'); break;
        case 'confirm-court-effect': if (!record.courtEffect) throw new Error('ยังไม่มีข้อมูลคำสั่งหรือคำพิพากษาศาล'); if (new Date(record.courtEffect.effectiveDate) > new Date(state.clock)) throw new Error('วันที่มีผลบังคับยังมาไม่ถึง จึงยังยืนยันไม่ได้'); record.courtEffect.confirmedBy = roleName(state.currentRole); record.courtEffect.confirmedAt = now(state); closeTasks(record, state, (item) => item.type === 'ConfirmCourtEffect'); setDimension(record, 'termination', 'ReviewingReasonAndEvidence', state, 'ยืนยันคำสั่งศาลมีผล', `วันที่มีผล ${record.courtEffect.effectiveDate} ไม่ใช้วันที่กดแทน`); openTask(record, state, 'ReviewTermination', 'ตรวจหลักฐานคำสั่งศาล', 'GotReviewer', 'termination', 'เจ้าของสำนวนยืนยันวันที่มีผลแล้ว', 2, 'High'); setCurrent(record, 'ตรวจเหตุยุติ', 'ตรวจหลักฐานคำสั่งศาล', 'GotReviewer'); break;
        case 'termination-ready': closeTasks(record, state); setDimension(record, 'termination', 'ReadyForSubmission', state, 'ยืนยันหลักฐานพร้อมเสนอ', 'บุคคล หมาย และหลักฐานครบถ้วน'); openTask(record, state, 'SubmitActivity7', 'ส่งแฟ้มเสนอผ่านกิจกรรมที่ 7', 'GotReviewer', 'termination', 'หลักฐานพร้อมเสนออนุมัติ', 2, 'High'); setCurrent(record, 'เสนออนุมัติภายใน', 'จัดทำ Package ส่งกิจกรรมที่ 7', 'GotReviewer'); break;
        case 'activity7-submit': closeTasks(record, state); record.terminationAttempts.push({ attempt: record.terminationAttempts.length + 1, sentAt: now(state), result: 'Pending', source: 'Activity7', packageRef: `A7-${record.systemRef}`, note: 'ส่ง Package ไปกิจกรรมที่ 7' }); setDimension(record, 'termination', 'SentToActivity7', state, 'ส่งข้อมูลไปกิจกรรมที่ 7', 'รอผลจากกิจกรรมที่ 7 โดยไม่มีปุ่มอนุมัติในหน้าปฏิบัติงาน'); setCurrent(record, 'รอผลอนุมัติภายใน', 'รอผลจากกิจกรรมที่ 7', null); break;
        case 'activity7-more-info': if (!options.presenter || !isPresenter()) throw new Error('จำลองผลภายนอกได้เฉพาะโหมดนำเสนอ'); setDimension(record, 'termination', 'Activity7RequestedInformation', state, 'รับผลกิจกรรมที่ 7 ขอข้อมูลเพิ่ม', 'เปิดงานให้ผู้รับผิดชอบจัดเตรียมข้อมูล'); openTask(record, state, 'ReviewTermination', 'จัดเตรียมข้อมูลเพิ่มตามผลกิจกรรมที่ 7', 'GotReviewer', 'termination', 'กิจกรรมที่ 7 ขอข้อมูลเพิ่ม', 3, 'Urgent'); setCurrent(record, 'เพิ่มเติมข้อมูล', 'จัดเตรียมและส่งข้อมูลเพิ่ม', 'GotReviewer'); break;
        case 'activity7-rejected': if (!options.presenter || !isPresenter()) throw new Error('จำลองผลภายนอกได้เฉพาะโหมดนำเสนอ'); closeTasks(record, state); setDimension(record, 'termination', 'InternallyRejected', state, 'รับผลไม่อนุมัติจากกิจกรรมที่ 7', payload.reason || 'เก็บเหตุผลและห้ามดำเนินการแจ้งยุติ'); setCurrent(record, 'ไม่อนุมัติภายใน', 'ตรวจเหตุผลและดำเนินการตามคำสั่ง', 'GotReviewer'); break;
        case 'activity7-approved': if (!options.presenter || !isPresenter()) throw new Error('จำลองผลภายนอกได้เฉพาะโหมดนำเสนอ'); closeTasks(record, state); setDimension(record, 'termination', 'InternallyApproved', state, 'รับผลอนุมัติจากกิจกรรมที่ 7', 'อนุมัติภายในแล้ว แต่ยังไม่ใช่ศาลถอนหมาย'); openTask(record, state, 'PrepareTerminationNotice', 'จัดทำหนังสือแจ้งยุติให้ตำรวจ', 'GotOfficer', 'termination', 'กิจกรรมที่ 7 อนุมัติภายในแล้ว', 2, 'High'); setCurrent(record, 'แจ้งยุติ', 'จัดทำและส่งหนังสือแจ้งหน่วยงาน', 'GotOfficer'); notify(record, state, 'InternalApprovalReceived', 'GotOfficer', 'ได้รับผลอนุมัติภายใน กรุณาจัดทำหนังสือแจ้งยุติ', 'termination'); break;
        case 'termination-notice': addDocument(record, state, 'TerminationNoticePolice', 'หนังสือแจ้งยุติให้ตำรวจ', 'Sent'); addDocument(record, state, 'TerminationNoticeAgency', 'หนังสือแจ้งสำนัก/กอง', 'Sent'); closeTasks(record, state, (item) => item.type === 'PrepareTerminationNotice'); setDimension(record, 'termination', 'PoliceAndAgencyNotified', state, 'บันทึกส่งหนังสือแจ้งยุติ', 'ส่งผ่านไปรษณีย์/นำส่งด้วยตนเอง และแยกจากคำสั่งศาล'); openTask(record, state, 'AgencyAcknowledge', 'รับทราบหนังสือแจ้งยุติ', 'AgencyCaseAdministrator', 'termination', 'มีหลักฐานว่าสำนัก/กองได้รับการส่งหนังสือ', 2, 'High'); openTask(record, state, 'SubmitWithdrawal', 'จัดทำรายงานศาลขอถอนหมาย', 'AgencyCaseAdministrator', 'termination', 'มีหลักฐานส่งหนังสือแจ้งแล้ว', 5, 'High'); setCurrent(record, 'รายงานศาล', 'สำนัก/กองจัดทำรายงานศาลขอถอนหมาย', 'AgencyCaseAdministrator'); notify(record, state, 'TerminationNoticeSent', 'AgencyCaseAdministrator', 'มีหนังสือแจ้งยุติและงานจัดทำรายงานศาล', 'termination'); break;
        case 'agency-ack': closeTasks(record, state, (item) => item.type === 'AgencyAcknowledge'); record.agencyAcknowledgement = { status: 'Acknowledged', by: roleName(state.currentRole), at: now(state), evidence: payload.evidence || 'เลขรับทราบ สปท.1/69' }; setDimension(record, 'termination', 'AwaitingCourtReport', state, 'สำนัก/กองรับทราบ', 'เก็บผู้รับ วันเวลา และหลักฐานรับทราบ'); setCurrent(record, 'รายงานศาล', 'จัดทำรายงานศาลขอถอนหมาย', 'AgencyCaseAdministrator'); break;
        case 'withdrawal-submit': addDocument(record, state, 'CourtWithdrawalReport', 'รายงานศาลขอถอนหมาย', 'Submitted'); record.withdrawalAttempts.push({ attempt: record.withdrawalAttempts.length + 1, submittedAt: now(state), channel: 'ยื่นด้วยตนเอง', receiptNo: payload.receiptNo || `ศอ-ถอน-${record.systemRef.slice(-3)}/69`, result: 'UnderConsideration', documents: record.documents.filter((item) => ['CourtWithdrawalReport', 'TerminationNoticeAgency'].includes(item.type)).map((item) => item.id) }); closeTasks(record, state, (item) => item.type === 'SubmitWithdrawal'); setDimension(record, 'termination', 'WithdrawalSubmittedToCourt', state, 'ยื่นรายงานศาลขอถอนหมาย', 'บันทึกวันยื่น ผู้ยื่น เลขรับ และหลักฐาน'); openTask(record, state, 'TrackWithdrawal', 'ติดตามผลคำร้องถอนหมาย', 'AgencyCaseAdministrator', 'termination', 'ยื่นรายงานศาลแล้ว', null, 'Normal'); setCurrent(record, 'รอผลศาล', 'ติดตามผลคำร้องถอนหมาย', 'AgencyCaseAdministrator'); break;
        case 'withdrawal-more-docs': record.corrections.push({ id: id('CR', state), source: 'WithdrawalCourt', detail: payload.detail || 'ศาลขอเอกสารประกอบเพิ่มเติม', assignedRole: 'AgencyCaseAdministrator', dueDate: payload.dueDate || '2026-08-10', status: 'Open' }); closeTasks(record, state); setDimension(record, 'termination', 'CourtRequestedDocuments', state, 'บันทึกศาลขอเอกสารเพิ่ม', 'เก็บรอบยื่นเดิมและเปิดงานจัดทำเอกสาร'); openTask(record, state, 'SubmitWithdrawal', 'จัดทำเอกสารเพิ่มเติมให้ศาล', 'AgencyCaseAdministrator', 'termination', payload.detail || 'ศาลขอเอกสารเพิ่ม', 3, 'Urgent'); setCurrent(record, 'เพิ่มเติมเอกสารศาล', 'จัดทำและยื่นเอกสารเพิ่มเติม', 'AgencyCaseAdministrator'); break;
        case 'withdrawal-resubmit': record.corrections.filter((item) => item.status === 'Open').forEach((item) => { item.status = 'Resolved'; item.response = 'แนบเอกสารเพิ่มเติมแล้ว'; }); addDocument(record, state, 'CourtWithdrawalReport', 'รายงานศาลขอถอนหมายฉบับเพิ่มเติม', 'Submitted'); record.withdrawalAttempts.push({ attempt: record.withdrawalAttempts.length + 1, submittedAt: now(state), channel: 'ยื่นด้วยตนเอง', receiptNo: `ศอ-ถอนเพิ่ม-${record.withdrawalAttempts.length + 1}/69`, result: 'UnderConsideration' }); closeTasks(record, state); setDimension(record, 'termination', 'AwaitingWithdrawalOrder', state, 'ยื่นเอกสารเพิ่มเติม', 'เพิ่ม Submission Attempt โดยไม่ลบรอบเดิม'); openTask(record, state, 'TrackWithdrawal', 'ติดตามคำสั่งถอนหมาย', 'AgencyCaseAdministrator', 'termination', 'ยื่นเอกสารเพิ่มเติมแล้ว', null, 'High'); setCurrent(record, 'รอคำสั่งถอน', 'ติดตามคำสั่งศาล', 'AgencyCaseAdministrator'); break;
        case 'withdrawal-order': { const orderNo = payload.orderNo || `คส.ถอน ${record.systemRef.slice(-3)}/2569`; const orderDate = payload.orderDate || '2026-08-04'; if (!orderNo || !orderDate) throw new Error('ต้องมีเลขคำสั่งและวันที่ถอนจากศาล'); const document = addDocument(record, state, 'WithdrawalOrder', 'คำสั่งถอนหมายจับ', 'Complete'); const attempt = record.withdrawalAttempts[record.withdrawalAttempts.length - 1] || { attempt: 1 }; Object.assign(attempt, { result: 'Withdrawn', orderNo, orderDate, court: record.court, documentId: document.id }); closeTasks(record, state); setDimension(record, 'termination', 'WithdrawnByCourt', state, 'ยืนยันคำสั่งถอนจากศาล', `เลขคำสั่ง ${orderNo} พร้อมวันที่และไฟล์ยืนยัน`); setCurrent(record, 'เสร็จสิ้น', 'ไม่มีงานเปิด', null); notify(record, state, 'WithdrawnByCourt', 'CaseOwner', 'ศาลมีคำสั่งถอนหมายแล้ว เปิดดูรายละเอียดใน E-CMIS', 'termination'); break; }
        case 'withdrawal-rejected': setDimension(record, 'termination', 'AwaitingCourtReport', state, 'บันทึกศาลไม่ถอนหมาย', payload.reason || 'ศาลมีคำสั่งอื่น เก็บผลและเปิดงานพิจารณาดำเนินการต่อ'); openTask(record, state, 'ReviewCourtWithdrawalResult', 'ตรวจผลศาลไม่ถอนหมาย', 'AgencyCaseAdministrator', 'termination', payload.reason || 'ศาลไม่ถอนหมาย', 3, 'High'); break;
        case 'withdrawal-court-transfer': { record.courtTransfer = { fromCourt: record.court, toCourt: payload.toCourt || 'ศาลจังหวัดตัวอย่าง', transferredAt: payload.transferredAt || now(state), evidence: payload.evidence || 'หนังสือแจ้งโอนคดีจากศาลเดิม' }; addDocument(record, state, 'CourtTransferOrder', 'หนังสือ/คำสั่งรับโอนคดีจากศาลอื่น', 'Received'); addAudit(record, state, 'บันทึกศาลรับโอนคดี', `โอนจาก ${record.courtTransfer.fromCourt} ไป ${record.courtTransfer.toCourt}`, 'Termination'); setDimension(record, 'termination', 'AwaitingCourtReport', state, 'บันทึกศาลรับโอนคดี', 'ต้องยื่นรายงานถอนหมายต่อศาลที่รับโอนคดีใหม่'); openTask(record, state, 'SubmitWithdrawal', 'จัดทำรายงานต่อศาลที่รับโอนคดี', 'AgencyCaseAdministrator', 'termination', 'ศาลรับโอนคดีแล้ว', 5, 'High'); setCurrent(record, 'รายงานศาล (รับโอนคดี)', 'จัดทำรายงานต่อศาลที่รับโอนคดี', 'AgencyCaseAdministrator'); break; }
        case 'day180-resolve': record.dataQuality.address = true; record.day180Issues.forEach((item) => { item.status = 'Resolved'; item.resolvedAt = now(state); }); closeTasks(record, state); setDimension(record, 'day180', 'DueAwaitingReview', state, 'แก้ไขคุณภาพข้อมูล', 'แนบหลักฐานที่อยู่และส่งกลับตรวจ'); openTask(record, state, 'ManageDay180', 'ตรวจรายชื่อครบ 180 วัน', 'GotOfficer', 'day180', 'ประเด็นคุณภาพข้อมูลได้รับการแก้ไข', 2, 'High'); setCurrent(record, 'ครบ 180 วัน', 'ตรวจรายชื่อก่อนจัดทำหนังสือ', 'GotOfficer'); break;
        case 'day180-screen': if (!Object.values(record.dataQuality).every(Boolean)) throw new Error('ยังมีข้อมูลไม่ครบหรือขัดแย้ง ไม่สามารถผ่านการคัดกรอง'); setDimension(record, 'day180', 'Screened', state, 'ผ่านการคัดกรอง 180 วัน', 'ผู้ตรวจยืนยันชื่อ เลขประชาชน ที่อยู่ และสถานะหมาย'); setDimension(record, 'day180', 'AwaitingLetter', state, 'เปิดงานจัดทำหนังสือ', 'รายการพร้อมเข้ารอบจัดทำหนังสือ'); openTask(record, state, 'ManageDay180', 'จัดทำหนังสือครบกำหนด 180 วัน', 'GotOfficer', 'day180', 'ผ่านการคัดกรองแล้ว', 3, 'High'); setCurrent(record, 'ครบ 180 วัน', 'จัดทำหนังสือถึงทะเบียนกลาง', 'GotOfficer'); break;
        case 'day180-block': record.day180Issues.push({ id: id('DQ', state), field: payload.field || 'ข้อมูลบุคคล', detail: payload.detail || 'ข้อมูลจากเอกสารไม่สอดคล้องกัน', status: 'Open', assignedRole: 'CaseOwner', dueDate: payload.dueDate || '2026-08-10' }); record.dataQuality.address = false; closeTasks(record, state); setDimension(record, 'day180', 'DataQualityBlocked', state, 'พักรายการจาก Batch', 'สร้าง Data Quality Issue แทนการเดาข้อมูล'); openTask(record, state, 'ResolveDataQuality', 'แก้ไขข้อมูลก่อนทำหนังสือ 180 วัน', 'CaseOwner', 'day180', payload.detail || 'ข้อมูลขัดแย้ง', 3, 'Urgent'); setCurrent(record, 'แก้ไขคุณภาพข้อมูล', 'ตรวจสอบข้อมูลและแนบหลักฐาน', 'CaseOwner'); break;
        case 'day180-letter': addDocument(record, state, 'Day180Letter', 'หนังสือถึงผู้อำนวยการทะเบียนกลาง', 'Draft'); addAudit(record, state, 'จัดทำร่างหนังสือครบ 180 วัน', 'ตรวจรายชื่อและสร้างเอกสารฉบับร่าง', 'Day180'); setCurrent(record, 'ครบ 180 วัน', 'ตรวจร่างและบันทึกการส่ง', 'GotOfficer'); break;
        case 'day180-send': { const type = payload.channel === 'Manual' ? 'Manual' : 'Postal'; record.dispatchAttempts.push({ attempt: record.dispatchAttempts.filter((item) => item.type === 'Day180Notice').length + 1, type: 'Day180Notice', channel: type, trackingNumber: type === 'Postal' ? (payload.trackingNumber || `TH18${record.systemRef.slice(-6)}9`) : null, sentAt: now(state), sentBy: roleName(state.currentRole), current: true, status: type === 'Postal' ? 'PostalAccepted' : 'ManualAwaitingReceipt', events: [] }); setDimension(record, 'day180', 'NoticeSent', state, 'บันทึกส่งหนังสือครบ 180 วัน', 'สำนักงาน ป.ป.ท. ส่งหนังสือแจ้งแล้ว ไม่ใช่ผลย้ายทะเบียน'); openTask(record, state, 'FollowDay180Receipt', 'ติดตามการรับหนังสือครบ 180 วัน', 'GotOfficer', 'day180', 'ส่งหนังสือแล้ว รอยืนยันรับ', 7, 'High'); setCurrent(record, 'ครบ 180 วัน', 'ติดตามการรับหนังสือ', 'GotOfficer'); notify(record, state, 'Day180NoticeSent', 'GotOfficer', 'ส่งหนังสือครบ 180 วันแล้ว กรุณาติดตามการรับ', 'day180'); break; }
        case 'day180-receipt': closeTasks(record, state, (item) => item.type === 'FollowDay180Receipt'); setDimension(record, 'day180', 'ReceiptConfirmed', state, 'ยืนยันรับหนังสือครบ 180 วัน', 'กรมการปกครองยืนยันรับหนังสือ ไม่ใช่ผลย้ายทะเบียนสำเร็จ'); setCurrent(record, 'ครบ 180 วัน', 'ติดตามผลดำเนินการเมื่อมีเอกสารตอบกลับ', 'GotOfficer'); break;
        case 'day180-followup': setDimension(record, 'day180', 'FollowUpOrResendRequired', state, 'เปิดงานติดตามหรือส่งซ้ำ', payload.reason || 'ยังไม่ได้รับการยืนยันรับหนังสือ'); openTask(record, state, 'FollowDay180Receipt', 'ติดตามหรือส่งหนังสือครบ 180 วันซ้ำ', 'GotOfficer', 'day180', payload.reason || 'ไม่ได้รับการยืนยัน', 2, 'Urgent'); setCurrent(record, 'ครบ 180 วัน', 'ติดตามหรือสร้างรอบส่งใหม่', 'GotOfficer'); break;
        default: throw new Error(`ยังไม่รองรับการดำเนินการ: ${action}`);
      }
      record.updatedAt = state.clock;
      return record;
    });
  }

  const orderPermissions = { 'order-create': 'manageExecutiveOrders', 'order-acknowledge': 'respondExecutiveOrder', 'order-progress': 'respondExecutiveOrder', 'order-escalate': 'manageExecutiveOrders', 'order-close': 'manageExecutiveOrders' };

  function performOrder(action, orderId, payload = {}, options = {}) {
    const permission = orderPermissions[action];
    if (!(options.presenter && isPresenter()) && permission && !window.Activity9Store.hasPermission(permission)) throw new Error('คุณไม่มีสิทธิ์ดำเนินการนี้ กรุณาติดต่อผู้รับผิดชอบตามขั้นตอน');
    return window.Activity9Store.mutate(`order:${action}`, (state) => {
      state.executiveOrders = state.executiveOrders || [];
      if (action === 'order-create') {
        if (!payload.subject) throw new Error('ต้องระบุเรื่องคำสั่งเร่งรัด');
        const recipientRole = payload.recipientRole || 'GotReviewer';
        const order = { id: id('EO', state), subject: payload.subject, recipientRole, recipientUnit: window.Activity9Seed.roles[recipientRole].unit, priority: payload.priority || 'High', dueDate: payload.dueDate || '2026-08-10', createdBy: roleName(state.currentRole), createdAt: now(state), status: 'Open', updates: [] };
        state.executiveOrders.unshift(order);
        return order;
      }
      const order = state.executiveOrders.find((item) => item.id === orderId);
      if (!order) throw new Error('ไม่พบคำสั่งเร่งรัดที่ต้องการ');
      if (action === 'order-acknowledge') { order.status = 'Acknowledged'; order.updates.unshift({ at: now(state), by: roleName(state.currentRole), note: payload.note || 'รับทราบคำสั่งเร่งรัด', status: 'Acknowledged' }); }
      else if (action === 'order-progress') { order.status = 'InProgress'; order.updates.unshift({ at: now(state), by: roleName(state.currentRole), note: payload.note || 'อยู่ระหว่างดำเนินการ', status: 'InProgress' }); }
      else if (action === 'order-escalate') { order.status = 'Escalated'; order.updates.unshift({ at: now(state), by: roleName(state.currentRole), note: payload.note || 'ยังไม่มีความคืบหน้าตามกำหนด จึงยกระดับและทวงถาม', status: 'Escalated' }); }
      else if (action === 'order-close') { order.status = 'Closed'; order.updates.unshift({ at: now(state), by: roleName(state.currentRole), note: payload.note || 'ดำเนินการครบถ้วนแล้ว', status: 'Closed' }); }
      else throw new Error(`ยังไม่รองรับการดำเนินการ: ${action}`);
      return order;
    });
  }

  window.Activity9StateMachine = { perform, performOrder, actionPermissions, actionRoles, label };
}());
